/*
[rewrite_local]
^https?:\/\/meivipapi\.icewx\.com\/.* url script-response-body SubPlayer.js
^https?:\/\/meivipapi\.icewx\.com\/.* url script-request-body SubPlayer.js
[mitm]
hostname = meivipapi.icewx.com
*/
const V={product_id:"1000003",app_store_product_id:"com.meijietech.subplayer.lifetime",vip_type:3,type:3,level:3,grade:3,vip_level:3,is_diamond:true,isDiamond:true,has_membership:true,hasMembership:true,has_lifetime_membership:true,hasLifetimeMembership:true,already_has_lifetime_membership:true,alreadyHasLifetimeMembership:true,is_continuous:false,is_vip:true,isVip:true,is_member:true,isMember:true,is_pro:true,isPro:true,is_premium:true,isPremium:true,is_paid_user:true,isPaidUser:true,is_lifetime:true,isLifetime:true,valid:1,status:1,active:true,expires_at_ms:4092599349000,expiresAtMs:4092599349000,expires_at:4092599349,expiresIn:999999999,expire_time_ms:4092599349000,expireTimeMs:4092599349000,expire_time:4092599349,remain_day:9999999,remainDay:9999999,is_expire:0,isExpire:0,is_expired:false,isExpired:false,order_id:"SPLIFETIME6666666666666666",transaction_id:"SPLIFETIMETXN666666666"};
const P=[{permission_type:"subtitle_generate",permissionType:"subtitle_generate",type:"subtitle_generate"},{permission_type:"subtitle_translate",permissionType:"subtitle_translate",type:"subtitle_translate"},{permission_type:"subtitle_asr",permissionType:"subtitle_asr",type:"subtitle_asr"},{permission_type:"adblock",permissionType:"adblock",type:"adblock"},{permission_type:"subtitle",permissionType:"subtitle",type:"subtitle"},{permission_type:"diamond",permissionType:"diamond",type:"diamond"},{permission_type:"pro",permissionType:"pro",type:"pro"},{permission_type:"ai_subtitle",permissionType:"ai_subtitle",type:"ai_subtitle"}];
const C={credit_balance:99999999,creditBalance:99999999,credit_points:99999999,creditPoints:99999999,credits:99999999,subtitle_points:99999999,subtitlePoints:99999999,subtitle_credit:99999999,subtitleCredit:99999999,subtitles_credits:99999999,subtitlesCredits:99999999,asr_credits:99999999,asrCredits:99999999,translate_credits:99999999,translateCredits:99999999,ai_credits:99999999,aiCredits:99999999,limit_exceeded:false,limitExceeded:false,usage_limit_exceeded:false,usageLimitExceeded:false,daily_limit_exceeded:false,dailyLimitExceeded:false,quota_exceeded:false,quotaExceeded:false,quota_used:0,quotaUsed:0,usage_used:0,usageUsed:0,remaining:99999999,remain:99999999,vip_expired:false,vipExpired:false,expired:false,is_expired:false,isExpired:false,expired_at:0,expiredAt:0,isLifetime:true,is_lifetime:true,hasLifetimeMembership:true,has_lifetime_membership:true,alreadyHasLifetimeMembership:true,already_has_lifetime_membership:true,is_diamond:true,isDiamond:true,vip_type:3,vipType:3,is_vip:true,isVip:true,is_member:true,isMember:true,is_pro:true,isPro:true,is_premium:true,isPremium:true,is_paid_user:true,isPaidUser:true,valid:1,active:true,expires_in:999999999,is_expire:0};
function D(o,b,d){if(!o||"object"!=typeof o)return o;d=d||0;if(d>8)return o;if(Array.isArray(o)){for(var i=0;i<o.length;i++)o[i]=D(o[i],b,d+1);return o}for(var k in b)b.hasOwnProperty(k)&&(o[k]=b[k]);["data","user","membership","credits","account","subscription","vip_info","vipInfo","status","info","detail","result","payload","user_info","userInfo","currentUser","profile","me"].forEach(function(n){if(o[n]&&"object"==typeof o[n])for(var p in b)b.hasOwnProperty(p)&&(o[n][p]=b[p])});for(var k in o)o.hasOwnProperty(k)&&o[k]&&"object"==typeof o[k]&&(o[k]=D(o[k],b,d+1));return o}
var u=$request.url||"";
if("undefined"!=typeof $request&&"undefined"==typeof $response){if(-1!==u.indexOf("/infoc/events")&&$request.body){var b=$request.body;b=b.replace(/"has_membership"\s*:\s*false/g,'"has_membership":true').replace(/"has_lifetime_membership"\s*:\s*false/g,'"has_lifetime_membership":true').replace(/"already_has_lifetime_membership"\s*:\s*false/g,'"already_has_lifetime_membership":true').replace(/"requires_membership"\s*:\s*true/g,'"requires_membership":false').replace(/"subtitle_requires_membership"\s*:\s*true/g,'"subtitle_requires_membership":false').replace(/"is_diamond"\s*:\s*false/g,'"is_diamond":true').replace(/"is_vip"\s*:\s*false/g,'"is_vip":true').replace(/"vip_type"\s*:\s*\d+/g,'"vip_type":3').replace(/"limit_exceeded"\s*:\s*true/g,'"limit_exceeded":false');$done({body:b})}else $done({})}
else if("undefined"!=typeof $response&&$response.body){var s=$response.body;
if(-1!==u.indexOf("/subtitle/translate")||-1!==u.indexOf("/subtitle/segment/create")||-1!==u.indexOf("/subtitle/segment/query")||-1!==u.indexOf("/segment/")||-1!==u.indexOf("/asr/")||-1!==u.indexOf("/subtitle/ai")){var oE=JSON.parse(s);D(oE,C,0);oE.code=0;oE.status="success";oE.message="success";oE.msg="success";oE.success=true;$done({body:JSON.stringify(oE)})}
else if(-1!==u.indexOf("/subtitle/credits/balancer")||-1!==u.indexOf("/subtitle/credits")||-1!==u.indexOf("/credits/")||-1!==u.indexOf("/balance")||-1!==u.indexOf("/quota")){var oC=JSON.parse(s);oC.data&&"object"==typeof oC.data&&Object.keys(C).forEach(function(k){oC.data[k]=C[k]});D(oC,C,0);$done({body:JSON.stringify(oC)})}
else if(-1!==u.indexOf("/account/compatible/refresh_token")||-1!==u.indexOf("/refresh_token")||-1!==u.indexOf("/auth/login")||-1!==u.indexOf("/auth/refresh")||-1!==u.indexOf("/login")||-1!==u.indexOf("/token")){var oD=JSON.parse(s);["data","user","account","profile"].forEach(function(n){if(oD[n]&&"object"==typeof oD[n])Object.keys(C).forEach(function(k){oD[n][k]=C[k]})});D(oD,C,0);$done({body:JSON.stringify(oD)})}
else if(-1!==u.indexOf("/usermix/user_info")||-1!==u.indexOf("/user/info")||-1!==u.indexOf("/user_info")){s=s.replace(/"nickname"\s*:\s*"[^"]*"/g,'"nickname":"QX_OK_\u5DF2\u89E3\u9501"').replace(/"user_name"\s*:\s*"[^"]*"/g,'"user_name":"QX_OK_\u5DF2\u89E3\u9501"').replace(/"userName"\s*:\s*"[^"]*"/g,'"userName":"QX_OK_\u5DF2\u89E3\u9501"').replace(/"username"\s*:\s*"[^"]*"/g,'"username":"QX_OK_\u5DF2\u89E3\u9501"').replace(/"vip_info_list"\s*:\s*\[\s*\]/g,'"vip_info_list":['+JSON.stringify(V)+"]").replace(/"vipInfoList"\s*:\s*\[\s*\]/g,'"vipInfoList":['+JSON.stringify(V)+"]").replace(/"membership_list"\s*:\s*\[\s*\]/g,'"membership_list":['+JSON.stringify(V)+"]").replace(/"subscriptions"\s*:\s*\[\s*\]/g,'"subscriptions":['+JSON.stringify(V)+"]").replace(/"order_list"\s*:\s*\[\s*\]/g,'"order_list":['+JSON.stringify(V)+"]").replace(/"permission_list"\s*:\s*\[\s*\]/g,'"permission_list":'+JSON.stringify(P)).replace(/"permissions"\s*:\s*\[\s*\]/g,'"permissions":'+JSON.stringify(P)).replace(/"permissionList"\s*:\s*\[\s*\]/g,'"permissionList":'+JSON.stringify(P));var o1=JSON.parse(s);D(o1,C,0);$done({body:JSON.stringify(o1)})}
else{try{var oF=JSON.parse(s);D(oF,C,0);$done({body:JSON.stringify(oF)})}catch(e){$done({})}}}
else $done({});
